name: Hello World #Nom du workflow

on: #Déclencheurs d'événements
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest #Machine virtuelle pour exécuter le job
    steps:
      - uses: actions/setup-node@v7
        with:
          node-version: '26.10'
        uses: actions/setup php

        run: echo "Github actions executed successfully" #Message de confirmation